sonata_admin:
    title: 'Sonata Admin'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, class: col-lg-3 col-xs-6, position: left }
            - { type: sonata.block.service.text, class: col-lg-9 col-xs-6, position: right }

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]

        sonata.block.service.text:
            settings:
                icon:  fa-magic
                text: <h2>Welcome to the Sonata Admin</h2>
                    <p>This is a <code>sonata.block.service.text</code> from the Block
                    Bundle, you can create and add new block in these area by configuring
                    the <code>sonata_admin</code> section.</p>
