twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'form/fields.html.twig'
        - 'bootstrap_3_horizontal_layout.html.twig'
