#homepage:
#    path: /
#    controller: App\Controller\DefaultController::index

homepage:
    path: /{_locale}
    controller: App\Controller\ArticleController::index
    defaults:   { _locale: en }
    requirements:
        _locale:  en|ru

