#index:
#    path: /
#    controller: App\Controller\DefaultController::index
      
blog_list:
  path:      /blog/list
  controller: App\Controller\ArticleController::bloglist
  
blog_show:
  path:      /blog/{slug}
  controller: App\Controller\ArticleController::show
  defaults:
      page: 1
  requirements:
      page: '\d+'
