#homepage:
#    path: /
#    controller: App\Controller\DefaultController::index

homepage:
    path: /{_locale}
    controller: App\Controller\HomeController::index
    requirements:
        _locale:  '%app_locales%'
    defaults:
        template: home/index.html.twig
        _locale: '%locale%'

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
