homepage:
    path: /
    controller: App\Controller\DefaultController::index
      
#blog_list:
#  path:      /blog/list
#  controller: App\Controller\ArticleController::blogList
  
#blog_article:
#  path:      /article/{slug}
#  controller: App\Controller\ArticleController::articleShow
#  defaults:
#      page: 1
#  requirements:
#      page: '\d+'
